### PR TITLE
Migrate to libtraceevent

### PR DESCRIPTION
**Pull request by flibitijibibo**
This attempts to move gpuvis to upstream libtraceevent. For the most part the API is the same, just with minor differences:

- There's now a `tep` namespace, with some structs being renamed accordingly (i.e. `pevent` is now `tep_handle`
- `tep_handle` is now opaque, with getters/setters replacing the public struct

trace_read.cpp _mostly_ translated really well, but `trace_clock` was completely removed which of course means there are some FIXMEs in this patch.

From their Git log...
```
    6921e57eabff567168600a1131eb64867f5da251
    libtraceevent: Remove tep_register_trace_clock()
    
    The tep_register_trace_clock() API is used to instruct the traceevent
    library how to print the event time stamps. As event print interface if
    redesigned, this API is not needed any more.  The new event print API is
    flexible and the user can specify how the time stamps are printed.
```

~Also on the TODO is reintroducing the tgid support from https://github.com/mikesart/gpuvis/commit/e4ee7daa5050d764a59eaba8fbb570e709149687 (and probably other commits I haven't found yet).~ Got it... just skipped the `SHOW_TGIDS` bit since that wasn't being used.

### CODE REVIEW

**Comment by flibitijibibo** [comment]
tgid support is back in... at least, the first version I found in the git log is now in. For trace_clock, from what I could tell trace_read only used the variable to get/set locally and does its own printing, so I just moved the variable to tracecmd_input. With that, everything builds and from what I can tell the program is working again.

So, just left with a couple items...

- Check for local trace-cmd changes (if any), reintroduce to libtraceevent
- Windows/macOS buildfixes

**Comment by flibitijibibo** [comment]
macOS and the first shot at Windows buildfixes are in. The Mac build was really easy, Windows was... well, the commit log should tell the story. This doesn't really go into the full log of fixes for Windows, but I was at least able to open up a trace without anything going wrong.

This is at least enough to start verifying for stability. Things I need to pull from the old trace-cmd source:

- Optimizations
- Windows fixes (thought I saw some for `sizeof(long)`?)

**Comment by flibitijibibo** [comment]
All the local changes to trace-cmd have been added back to the local copy of libtraceevent. A couple changes were found in upstream and so were skipped.

With the exception of the bizarre thing I found in 3201e23 and maybe some tab/space errors, this should now function as it did before including performance (unless upstream regressed in some way).

**Comment by flibitijibibo** [comment]
Force-pushed a cleaned up commit history so that this can be merged automatically.

**Comment by mikesart** [comment]
Is this something I could try to get into master @flibitijibibo? Thanks much!

**Comment by flibitijibibo** [comment]
Yup, everything looked good when I last checked it out! It might be worth rebasing libtraceevent one more time, but I marked down the current revision so it's not urgent for the merge IMO.

**Comment by mikesart** [comment]
Awesome. I'll get on this now. Thanks again, really appreciate the help!

**Pull request closed without merging**
